= HID UPS Power Device Library for Arduino =


https://projecthub.arduino.cc/abratchik/hid-compliant-ups-with-arduino-3e597a


This library allows an Arduino board with USB capabilities to act as a HID-compliant UPS according to USB HID specifications. 
The library is useful if you want to build a smart UPS or other power device, which can report its state to the PC host
or perform power on/power off operations as necessary for your project.

For more information about USB HID specs please read https://www.usb.org/sites/default/files/pdcv11.pdf

== Supported Arduinos ==
* Leonardo
* (Pro)Micro

== Setup & Usage ==
Setup is very simple. Just clone this repository to Arduino libraries, then upload the sketch UPS.ino 
from the /examples folder. Once upload is completed successfully you will find HID Device Battery in  
your system.

You migth need to change `bCapacityMode` from `2` (%) to `1` (mWh) if you want Windows to report battery capacity percentage on laptops that already has a battery installed (see https://github.com/abratchik/HIDPowerDevice/issues/11).

== Ethernet-controlled UPS simulator ==

The `examples/UPS_Simulator_Ethernet` sketch turns a Leonardo plus W5500 Ethernet shield into a remotely controlled USB HID UPS simulator.
The USB connection remains the UPS interface to the host under test, while Ethernet TCP port `5000` is used to inject simulated AC failure,
battery capacity/runtime, low-battery, overload, replacement-battery, communication-loss and shutdown conditions. Hardware UART (`Serial1`) provides
a bench-control fallback using the same command protocol.

The simulator starts disarmed in a safe online/100% state. Use `ARM ON` before changing UPS state; `ARM OFF` or `RESET` restores the safe state.
See `docs/ETHERNET_SIMULATOR.md` for wiring, power, protocol, test sequences and Nut-ups integration notes.

The Leonardo build is verified by GitHub Actions. The Ethernet simulator currently uses about 96% of available Leonardo flash, so substantial future features
should be moved to a native-USB MCU with more program memory rather than expanding the AVR build indefinitely.

== Additional setup step on Linux hosts ==
Copy linux/98-upower-hid.rules file to the /etc/udev/rules.d/ folder , then reboot. This is required for
Linux device manager (udev) to recognize the Arduino board as UPS. 


== Tested on Operating Systems ==
* Mac OSX 10.14.6 Mojave
* Ubuntu 18.04.05 LTS 
* Windows 10

== License ==

Copyright (c) Alex Bratchik 2020. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
